const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let quiet=false,cancelled=0,last,source={left:115,top:124,width:54,height:54};
const listeners={};
const dialog={open:false,dataset:{},scrollTop:100,showModal(){this.open=true},close(){this.open=false;listeners.close()},getBoundingClientRect(){return {left:252,top:16,width:820,height:726}},animate(frames,options){let resolve,reject;const finished=new Promise((a,b)=>{resolve=a;reject=b});last={frames,options,resolve,reject};return {finished,cancel(){cancelled++;reject(new Error('cancelled'))}}},addEventListener(name,fn){listeners[name]=fn}};
const window={};
vm.runInNewContext(fs.readFileSync('dist/window-motion.js','utf8'),{window,Promise,matchMedia:()=>({matches:quiet}),getComputedStyle:()=>({borderRadius:'11px',opacity:'1',transform:'none'}),document:{body:{classList:{contains:()=>false}},querySelectorAll:()=>[dialog]}});
const trigger={querySelector:()=>({getBoundingClientRect:()=>source})};
(async()=>{
 window.openPortfolioWindow(dialog,trigger);assert.equal(dialog.open,true);assert.equal(dialog.scrollTop,0);
 assert.match(last.frames[0].transform,/translate\(-520px,-228px\) scale\(/);last.resolve();await Promise.resolve();
 let closing=window.closePortfolioWindow(dialog);
 assert.equal(dialog.open,true,'Native modal remains open throughout retraction');assert.equal(last.options.duration,300);
 assert.match(last.frames[1].transform,/translate\(-520px,-228px\) scale\(/);
 assert.equal(window.closePortfolioWindow(dialog),closing,'Repeated close shares its pending transition');
 last.resolve();assert.equal(await closing,true);assert.equal(dialog.open,false);
 window.openPortfolioWindow(dialog,trigger);closing=window.closePortfolioWindow(dialog);
 window.openPortfolioWindow(dialog,trigger);assert.equal(await closing,false,'Reopening cancels stale close');assert.equal(dialog.open,true);
 last.resolve();await Promise.resolve();source={left:20,top:100,width:44,height:44};
 closing=window.closePortfolioWindow(dialog);assert.match(last.frames[1].transform,/translate\(-620px,-257px\)/,'Return target follows responsive icon position');last.resolve();await closing;
 quiet=true;window.openPortfolioWindow(dialog,trigger);assert.equal(last.options.duration,100);assert.equal(last.frames[0].transform,undefined);
 closing=window.closePortfolioWindow(dialog);assert.equal(last.options.duration,90);assert.equal(last.frames[1].transform,undefined);last.resolve();await closing;
 assert.equal(dialog.open,false);assert.ok(cancelled>0);
 console.log('Window motion: open/close origin, modal lifetime, repeated close, reopen race, resize and reduced motion passed.');
})().catch(e=>{console.error(e);process.exitCode=1});
